[kubernetes]
format = 'on [⛵ $context](dimmed green) '
disabled = false
#contexts = [
#  { context_pattern = "juvo-dev", style = "green", symbol = "" },
#]

[azure]
disabled = false
format = 'on [$symbol($subscription)]($style) '
symbol = '󰠅 '
style = 'blue bold'
