#[azure]
#disabled = false
#format = 'on [$symbol($subscription)]($style) '
#symbol = '󰠅 '
#style = 'blue bold'

[kubernetes]
disabled = false
contexts = [
  { context_pattern = "*juvo-dev*", style = "green" },
  { context_pattern = "*juvo-ilab-prod*", style = "red bold" },
]
format = '[$symbol$context( \($namespace\))]($style) in '
